apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-crds-helm
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: agentgateway-crds
    helm:
      skipCrds: false
    repoURL: ghcr.io/kgateway-dev/charts
    targetRevision: v2.2.0-main
  syncPolicy:
    automated:
      # Prune resources during auto-syncing (default is false)
      prune: true
      # Sync the app in part when resources are changed only in the target Kubernetes cluster
      # but not in the git source (default is false).
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
