apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway-helm
  namespace: argocd
spec:
  destination:
    namespace: agentgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: agentgateway
    helm:
      skipCrds: false
    repoURL: ghcr.io/kgateway-dev/charts
    targetRevision: v2.2.0-main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
